# Variable 

a = 1

b = 2

print(a+b)

# Datatype 

a = 3             # This is an integer

b = 5.34          # This is a float

c = " Mahadev"    # This is a string

d = True          # This is a booleane 

e = None          # This is a NoneType

# RULE S FOR VARIABLE NAME

b = 34 

bbb = 56

nishu = 78

_nishu = 98

nishu9 = 89 

nishu_9 = 78

n_ishu = 78

#n ishu = 89     INVALID 

#@nishu = 88     INVALID 

# 99nishu = 99   INVALID 

# OPERATORS 

# ARITHMETIC OPERATORS

a = 78 
b = 22
c = a+b 
print(c)

# ASSIGNMENT OPERATORS

A = 78-18 # ASSIGN 78 - 18 IN A 
B = 33 
B += 4 
B -=5 # Increment the value of b by 4 and then assign it to b 
A *=2 
print(A)
print (B)


# COMPARISON OPERATORS

# WRITEEN VALUE ALWAYS IN TRUE OR FALSE 

S = 5<3
V = 5>3
T = 6<=6
G = 8!=8
H = 6==6

print(H)
print(G)
print(T)
print(S)
print(V)

#LOGICAL OPERATOR 

#OR 
w = True or False 
print(w)

#TRUTH TABLE OF 'OR'

print("True or False is ", True or False)
print("True or True is ", True or True) 
print("False or False is ", False or False)
print("False or True is ", False or True)

# AND 
s = True and False 
print(s)

# TRUTH TABLE OF 'AND'

print("True and False is ", True and False)
print("True and True is ", True and True) 
print("False and False is ", False and False)
print("False and True is ", False and True)


# Not 

print(not(True))
print(not(False))

# TYPECASTING 

q = 22
r = type(q)

y = 45.88
u = type(y)

i = "Vishvraj"
o = type(i)

print(o)
print(u)
print (r)

#CONVERT DATA TYPE 

f = "88.3"
j = type(f)

k = "88.7"
l = float(k)
n = type (l)

print(j)
print(n)

z = 67
x = str(z)
m = type(x)
print(m)

# INPUT FUNCTION 
c = input("Enter number 1 :")
d = input("Enter number 2 :")

print("Number c is ", c)
print("Number d is ", d)
print("Sum is ", c+d) # This will concatenate the two strings

# To get the actual sum, we need to convert the input strings to integers

c = int(input("Enter number 1 :"))
d = int(input("Enter number 2 :"))

print("Number c is ", c)
print("Number d is ", d)
print("Sum is ", c+d) # This will give the actual sum of the two numbers





